CREATE TABLE Vairuotojas (
	vairuotojo_ID		INTEGER
				GENERATED BY DEFAULT AS IDENTITY (START WITH 200000 INCREMENT BY 1),
	vardas			VARCHAR(20),
	pavarde			VARCHAR(20),
	telefono_numeris	VARCHAR(12),

	PRIMARY KEY (vairuotojo_ID)
);

CREATE TABLE Sunkvezimis(
	sunkvezimio_ID		INTEGER
				GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1),
	vairuotojo_ID		INTEGER NOT NULL,
	marke			VARCHAR(10)
				CHECK(marke IN ('Volvo', 'MAN', 'Scania', 'Iveco', 'DAF')),
	rida			INTEGER,
	talpa			INTEGER,
	euro_standartas		SMALLINT,
	laisvas			BOOLEAN DEFAULT TRUE,

	FOREIGN KEY (vairuotojo_ID) REFERENCES Vairuotojas (vairuotojo_ID),
	PRIMARY KEY (sunkvezimio_ID)
);

CREATE TABLE Klientas (
	kliento_ID		INTEGER NOT NULL
				GENERATED BY DEFAULT AS IDENTITY (START WITH 300000 INCREMENT BY 1),
	pavadinimas		VARCHAR(50),
	kontaktinis_nr		VARCHAR(12),
	sandelio_adresas	VARCHAR(255),

	PRIMARY KEY (kliento_ID)
);

CREATE TABLE Uzsakymai (
	uzsakymo_ID		INTEGER NOT NULL
				GENERATED BY DEFAULT AS IDENTITY (START WITH 400000 INCREMENT BY 1),
	sunkvezimio_ID		INTEGER NOT NULL,
	kliento_ID		INTEGER NOT NULL,
	uzsakymo_data		DATE DEFAULT CURRENT_DATE,
	pristatymo_terminas	DATE DEFAULT CURRENT_DATE + 30,
	krovinio_dydis		INTEGER DEFAULT 100,
	pristatymo_adresas	VARCHAR(255),
	atstumas		INTEGER,
	numatyta_kaina		INTEGER,
	
	FOREIGN KEY(sunkvezimio_ID) REFERENCES Sunkvezimis (sunkvezimio_ID),
	FOREIGN KEY(kliento_ID) REFERENCES Klientas (kliento_ID),
	PRIMARY KEY(uzsakymo_ID)
);

CREATE UNIQUE INDEX Index_klientai ON Klientas(pavadinimas);

CREATE INDEX Index_Sunkvezimis ON Sunkvezimis(marke);
